### ISSUE TITLE
Notes from Meeting at HighTechKids

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#505]
On June 7, 2016 I met with Vicki and Jeannie from HighTechKids and went over the software and documentation. Below are the notes that I took. Each checkbox is an action that needs to be dealt with. In some cases I will open separate tickets and note them here.

# terminology

Ticket #496

Event division is confusing.
"Award grouping" -> needs to be changed everywhere in code
Ask user how many sets of awards?
Minimize the use of the names, only use where really needed and don't make them the same as the judging group yet.
eg. AG1, AG2
Award groupings have judging groups.
Anytime you have more than 1 judging group in an award grouping you need to do callbacks.

Add examples to the bottom of the page with our tournaments.
Make a picture with boxes.
Don't use Minnesota specific names.
Put numbers of teams.
Award groups - 1, 2, 3
judging groups - A, B, C

## playoffs
Ticket #497

Use playoff brackets instead of playoff division.

# setup instructions

* [x] Need multiple pages

 Have Jeanne and Vicki read this after splitting into multiple pages and rewrite.
This will be done with the next release.

# edit tournaments

* [x] help for edit tournaments, should say "team upload" so language is consistent.
* [x] "Short Name" "Detailed Name"
* [x] Check if single quotes are properly handled in names

# display tournament assignments

* [x] Need help text
* [x] Optional step
* [x] Still references division column.

# setup

* [x] Doesn't tell that upload database will stomp everything.
* [x] Would be really nice to not have the warning when the database doesn't already exist.

# schedules on the web
* [x] Should open new windows so that back works?
* [x] Need to change "div" header to "award group"

## choose subjective headers

* [x] "schedule columns from the data file"
* [x] Use drop downs like in the team upload. Match subjective categories to schedule file columns. Look at words from team upload.

## ask about award groups

* [x] would you like to assign award groups based upon the information in the schedule?
* [x] Commit page needs to remove "divisions".
* [x] Note that you can edit team information later.

# edit team
* [x] "judging station" -> "judging group"
* [x] Need this everywhere

# import team datafile
* [x] Skip filtering of data file. Tell them to trim the data file for just the teams they want.
* [x] Event division -> award group
* [x] judging station -> judging group
* [x] Make clear that titles need to be on the first row.
* [x] Change "Database column" to "Software information"
* [x] Match the database columns on the left with the names of the columns from your data file.
* [x] Note that when initial tournament is not specified the judging station and event division still get copied over.

# edit divisions

* [x] Should go to admin page after commit

# scoreboard
* [x] Change background color of score display text
* [x] Sort all teams by team number.
* [x] Remove "all teams by alphabetical" - give this space to the score page text
* [x] Take "Division" out of all pages, just use names.

# judging groups...
* [x] be able to edit judging groups

# finalist scheduling
* [x] Make sure this is described. -> ticket #498

# training

* [x] Add tournament name(s) to sample file. -> ticket #499

# assign table labels

* [x] Crashed for vicki ticket #504

# admin
* [x] Make success message larger and obvious (color).
* [x] subjective web app launch. Should be in a new window from admin.
* [x] DONE is not clear enough, perhaps make checkbox or grey out.

## add team

* [x] Add help text - this should not be used very often.
* [x] Should check team number in real-time. New ticket. -> ticket #500

## score page text
* [x] "Scoring display text"
* [x] Needs help text.

# instructions for running software

* [x] Merge documentation with detailed subjective documentation
* [x] Need more sub headings

# subjective data download
ticket #501

Edge browser in windows 10 renamed extension to .zip. Why?

# initialize playoffs

* [x] Add documentation about how to enter score or what would happen if they left.
* [x] Check verified!
* [x] Link to the performance score entry page (new window).

* [x] Remove reference to divisions. Just make sure all scores are entered.
* [x] Change check seeding rounds to check all teams.

* [x] "division" is "select bracket" This assumes that the brackets are defined.

* [x] Help for uninitalize, make sure to not use if not needed.

# remote control of display
ticket #502

Doesn't seem to be working in Edge browser. Test this.

# scheduler

* [x] First prompt for columns should have more descriptive text.
* [x] Would be nice if general schedule showed the end times.
* [x] "print score sheets" -> "write score sheets"
* [x] Make column chooser a column model like the web interface.
* [x] Schedule list doesn't show team name, it should.
* [x] change time - specify that this is per team
* [x] Time between performance label is missing text.
* [x] Write down excel stuff for Vicki & Jeanne.

ticket #503 Be able to create a schedule from scratch. Need save as.

# for state
Make playoff brackes be "mosquitos" and "loons".
Will the kids understand what group they go in?
